spring.application.name=ph
spring.datasource.url=jdbc:postgresql://localhost:5432/tradingDB
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
